### ISSUE TITLE
parse_remote needs to use parse host not remote to separate port

### ISSUE THREAD

**Issue by mhoffma** [micropython/webrepl#26]
mmh@pluto:~/esp/webrepl$ git diff
diff --git a/webrepl_cli.py b/webrepl_cli.py
index 04e0591..03b5a9f 100755
--- a/webrepl_cli.py
+++ b/webrepl_cli.py
@@ -185,7 +185,7 @@ def parse_remote(remote):
         fname = "/"
     port = 8266
     if ":" in host:
-        host, port = remote.split(":")
+        host, port = host.split(":")
         port = int(port)
     return (host, port, fname)

**Comment by mhoffma** [comment]
sorry about the formating can I just submit it?

**Comment by dpgeorge** [comment]
Thanks for the patch, fixed in 0e1209aefd51ee8402dc79231ca772d94b5d9700.
