### ISSUE TITLE
`webrepl_cli.py` freezes on connection.

### ISSUE THREAD

**Issue by skorokithakis** [micropython/webrepl#7]
It looks like `webrepl_cli` expects a `:` for some sort of login prompt, but it never gets it. The received data is:

~~~
WebREPL connected
>>>
~~~

**Comment by dpgeorge** [comment]
Do you have the latest version of the ESP8266 firmware on your device?  Please erase all flash (esptool.py erase_flash) before downloading the firmware to make sure everything works correctly.

**Comment by skorokithakis** [comment]
I tried both the latest released version and the latest HEAD (as of last night). I also erased the flash, but I'll try again.

**Comment by dpgeorge** [comment]
Can you pleas explain exactly what steps you run (on both side) to get the error?

**Comment by skorokithakis** [comment]
I turn the freshly-flashed ESP8266 on, I connect to the REPL via serial, connect it to the WiFi network, and run:

~~~
import webrepl
webrepl.start()
~~~

Then:

~~~
15:04:25 $ webrepl_cli.py misc/car.py 192.168.10.25:/boot.py
put 192.168.10.25 8266
misc/car.py -> /boot.py
~~~

It just freezes there. Output in the serial console is:

~~~
WebREPL connection from: ('192.168.10.149', 37472)
WebREPL connected
>>> /boot.pyWA
~~~

and stepping through the `webrepl_cli.py` code reveals that it gets stuck in `login` while waiting for a colon to come through, but one never does. However, even disabling the login method gets stuck on the socket `recv` after having sent the file.

**Comment by dpgeorge** [comment]
Ok, because it's a fresh device the webrepl is asking you for a password (but webrepl_cli doesn't understand that).  Two options to work around this:

1) First login via webrepl terminal (http://micropython.org/webrepl) to set the password.  Then use webrepl_cli.
2) Start webrepl with a given password, eg: `webrepl.start(password='micro')`

**Comment by skorokithakis** [comment]
Alas:

~~~
>>> import webrepl
>>> webrepl.start(password="pass")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function does not take keyword arguments
>>> webrepl.start("pass")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "webrepl", line 53, in start
  File "webrepl", line 16, in setup_conn
TypeError: can't convert str to int
~~~

**Comment by dpgeorge** [comment]
Very strange... try: `webrepl.start(8266, "pass")`

**Comment by skorokithakis** [comment]
~~~
>>> webrepl.start(8266, "pass")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function takes 1 positional arguments but 2 were given
>>> webrepl.start(8266, password="pass")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function does not take keyword arguments
~~~

**Comment by dpgeorge** [comment]
You must have an old version of webrepl.py, before passwords were introduced.  Delete scripts/webrepl* and rebuild.

**Comment by skorokithakis** [comment]
There *is* no `scripts/webrepl*`, though.

https://github.com/micropython/micropython/tree/master/esp8266/scripts

**Comment by dpgeorge** [comment]
Yes, it was recently moved to the modules/ subdirectory.  If there was something remaining in scripts/ then it would override modules/.  Also, if you have webrepl.py on your local filesystem on the device it wall also override the built-in one.  Look for the function start() in modules/webrepl.py and see if it is the latest.  Otherwise the only thing I can think of is that you reclone the micropython repo and rebuild.

**Comment by skorokithakis** [comment]
The repo looks okay (it's the same as what's on github). I'll remove the build dir entirely and try again, maybe there was some cruft there from a previous build, thanks.

**Comment by skorokithakis** [comment]
I just used the 1.8.2 binary (removing everything and compiling the latest master gave me a compilation error) and it worked, who knows what went wrong. Thank you.
