### ISSUE TITLE
webrepl setup fails on picow/rp2

### ISSUE THREAD

**Issue by ingelumer** [micropython/webrepl#74]
Hello all,

based on this post [top: Make all network-capable boards use bundle-networking. #10592](https://github.com/micropython/micropython/pull/10592) I installed the latest rpi2 build [v1.19.1-859-g41ed01f13 (2023-02-09) .uf2](https://micropython.org/resources/firmware/rp2-pico-w-20230209-unstable-v1.19.1-859-g41ed01f13.uf2) on my picow.

When I try to initialize webrepl by entering `import webrepl_setup` in the thonny shell I am getting below error.
Please any idea what I am doing wrong?

```
>>> import webrepl_setup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "webrepl_setup.py", line 1, in <module>
  File "webrepl_setup.py", line 1, in main
  File "webrepl_setup.py", line 1, in get_daemon_status
OSError: [Errno 2] ENOENT
```

**Comment by dpgeorge** [comment]
I think you need to add a `boot.py` to the root directory of your filesystem on the rp2 board.  It can be an empty file.

**Comment by jordanarpad** [comment]
thank you @dpgeorge - indeed an empty boot.py did the trick on my pico: `import webrepl_setup` successfully run and saved `PASS` in `webrepl_cfg.py`. After reboot port 8266 on my pico was opening webrepl webpage where I could connect with the configured `PASS`. Interestingly it entered raw REPL mode and had to press Ctrl-B to go to normal mode.

**Comment by ingelumer** [comment]
adding the empty `boot.py` file helped a lot, thank you!

The `webrepl_cfg.py` was created and I added wlan init to the `boot.py` file in order to make it work completely.
Original boot.py was added just two lines:
```
import webrepl
webrepl.start()
```
